### ISSUE TITLE
Create Landing Page

### ISSUE THREAD

**Issue by rsgc-wrana-m** [rsgc-wrana-m/SSAS#1]
create a simple landing page that allows a user to choose whether they are a student or teacher, and login accordingly.  At this stage we are simply focusing on the back-end design rather than the styling

**Comment by rsgc-wrana-m** [comment]
Closed with other commit

**Comment by rgordonathome** [comment]
What commit? Please do not close issues without a link or other evidence of work completed.

Requires a label and an assignee.

**Comment by rsgc-wrana-m** [comment]
added label and assigned myself
