### ISSUE TITLE
Student home page is very "empty" with no missions

### ISSUE THREAD

**Issue by rgordonathome** [rsgc-wrana-m/SSAS#114]
Without any missions, the student home page is quite sparse.

When this is the case, a brief message in the middle of the screen would go a long way to telling the user that everything is working, it's just that they have no missions available / accepted.

![screen shot 2016-04-17 at 2 38 39 pm](https://cloud.githubusercontent.com/assets/2380516/14589209/39502830-04aa-11e6-9ef3-b0b925f78ec5.png)

**Comment by rsgc-wrana-m** [comment]
The design of the assignment is in such a way where all the missions are created before students have access, meaning there will never be no missions avaliable
