### ISSUE TITLE
Create some navigational cues

### ISSUE THREAD

**Issue by rgordonathome** [rsgc-wrana-m/SSAS#119]
Right now, for example, when you are the teacher and you click the "Student List" link, you go to the teacher landing page, and there is no title to indicate where you are:

![screen shot 2016-04-17 at 2 58 37 pm](https://cloud.githubusercontent.com/assets/2380516/14589310/e5fd462e-04ac-11e6-811c-7fbd5dc7cec7.png)

Then:

![screen shot 2016-04-17 at 2 59 04 pm](https://cloud.githubusercontent.com/assets/2380516/14589316/f2b543d0-04ac-11e6-9726-a774becce307.png)

**Comment by rsgc-wrana-m** [comment]
1f2634f5306445d133df3f92fd5f0e5ee175e56e
