### ISSUE TITLE
Show user the prototype of the website

### ISSUE THREAD

**Issue by rsgc-molloy-c** [rsgc-wrana-m/SSAS#12]

**Comment by rsgc-molloy-c** [comment]
http://imgur.com/a/glqZ2

**Comment by rsgc-molloy-c** [comment]
http://imgur.com/a/glqZ2
https://www.youtube.com/watch?v=Pi-KPN1h1Fs

**Comment by rgordonathome** [comment]
What was the specific feedback received? This should be documented in your [Product Backlog page](../wiki/Product-Backlog).

A label and an assignee is required.

**Comment by rgordonathome** [comment]
Here is what I observed in his feedback:

– comments from Mr. Darvasi on logo that nurses use
– possibly adjust colour scheme
– limit how many missions a student can have active at any given time
– interface seems complete and looks really good

Some feedback from me on the prototyping session – seems like you had a pretty complete teacher prototype – but you were too directed in conducting the prototyping session.

You should be sitting back and letting the user interact with the site, without prompting from you. Observe what he says when interacting with your paper prototype. If he has to ask too many questions then your interface is not intuitive and requires changes.

I have noted that nothing changed on your product backlog page after my comments on Dec 14 – I am not convinced that you have really committed to the idea of conducting interface testing.
