### ISSUE TITLE
change hyperlink in forgot password

### ISSUE THREAD

**Issue by rsgc-molloy-c** [rsgc-wrana-m/SSAS#14]

**Comment by rsgc-wrana-m** [comment]
Fixed with a previous commit

**Comment by rgordonathome** [comment]
Is this a bug fix? Please label as appropriate. Who was this assigned to?

Please close the issue by linking to the commit. 

You can simply paste the URL from the commit in the comment field.

**Comment by rsgc-wrana-m** [comment]
assigned myself
