### ISSUE TITLE
Show Teacher Paper Prototype

### ISSUE THREAD

**Issue by rsgc-wrana-m** [rsgc-wrana-m/SSAS#20]

**Comment by rgordonathome** [comment]
Where is the video of this work?

What was the feedback given? 

A link to the video of the session must be provided, and a list of the feedback provided must be documented. The wiki should be adjusted as necessary based on feedback given.

**Comment by rgordonathome** [comment]
Is this a duplicate of issue #12?

**Comment by rsgc-molloy-c** [comment]
https://www.youtube.com/watch?v=LL88_jHoJss&list=LLyzm7-M3PaCEw9hQd7efMDw&index=1

**Comment by rsgc-molloy-c** [comment]
https://www.youtube.com/watch?v=LL88_jHoJss&list=LLyzm7-M3PaCEw9hQd7efMDw&index=1
