### ISSUE TITLE
Develop Create Account/Login System

### ISSUE THREAD

**Issue by rsgc-wrana-m** [rsgc-wrana-m/SSAS#3]
This will allow students (not teachers) to create their own account on the website, and then 
login to (log in to) (log into) it.  Teacher accounts can only be created by a database administrator.

**Comment by rgordonathome** [comment]
This issue requires an assignee and a label.

What you are looking at is user authentication and session management.

[User authentication was described with the example code provided here](https://github.com/rsgc-ics4u-2015/site-with-authentication).

Over the holiday, I will be extending that example to include session management (essentially, determining whether a user is logged in or not when they 'land' on a page that should be in a protected part of the website).
