### ISSUE TITLE
Create Simple Login Page (without session handling)

### ISSUE THREAD

**Issue by rsgc-wrana-m** [rsgc-wrana-m/SSAS#44]

**Comment by rsgc-wrana-m** [comment]
Logging in with a correct password, will now direct the user to the student landing page.

Since I don't have proper screen recording software, here is a gif of this in action:https://gyazo.com/1944b5ca313fb4abb83015fd40dee9e3

**Comment by rgordonathome** [comment]
Just a head's up @rsgc-wrana-m you can use QuickTime Player to record your screen:

https://support.apple.com/en-ca/HT201066

... but the animated GIF works well too.
