### ISSUE TITLE
Create a mockup homepage 

### ISSUE THREAD

**Issue by rsgc-molloy-c** [rsgc-wrana-m/SSAS#5]
Need to find a good photo and a design that the user likes

**Comment by rsgc-wrana-m** [comment]
Found appropriate photo and created simple design

**Comment by rgordonathome** [comment]
Close by including a photo or screenshot of the prototype.

Requires a label and an assignee.

**Comment by rsgc-wrana-m** [comment]
assigned myself

**Comment by rgordonathome** [comment]
This issue was not closed with any evidence of the work being completed.

See my comment on Dec 14.

**Comment by rsgc-wrana-m** [comment]
<img width="1415" alt="screen shot 2016-02-24 at 12 14 40 pm" src="https://cloud.githubusercontent.com/assets/14296608/13294045/3239bb12-daf0-11e5-8091-aaf513593e80.png">
