### ISSUE TITLE
Fix printing of code

### ISSUE THREAD

**Issue by rsgc-wrana-m** [rsgc-wrana-m/SSAS#50]
The first line of php is an echo statement, which is not echoed, and the first section of html is a small seemingly randomly selected piece of the php code written for user registration

**Comment by rsgc-wrana-m** [comment]
Fixed at lunch with Mr. Gordon's assistance

**Comment by rgordonathome** [comment]
This needs be closed via a commit.

**Comment by rsgc-wrana-m** [comment]
Closed via commit: 60db3afc0a9ad60d718aad0d386f6aee814a0d8c
