### ISSUE TITLE
create a reigister page

### ISSUE THREAD

**Issue by rsgc-molloy-c** [rsgc-wrana-m/SSAS#6]

**Comment by rsgc-wrana-m** [comment]
created

**Comment by rgordonathome** [comment]
What do you mean by 'create a register page'?

If this was a paper prototype, close by including a photo of the prototype. If an HTML/CSS prototype, close by linking to a commit.

Requires a label and an assignee.

**Comment by rsgc-wrana-m** [comment]
assigned myself

**Comment by rgordonathome** [comment]
Closed without any evidence.
