### ISSUE TITLE
Create a Login page

### ISSUE THREAD

**Issue by rsgc-wrana-m** [rsgc-wrana-m/SSAS#7]

**Comment by rsgc-wrana-m** [comment]
Completed login page

**Comment by rgordonathome** [comment]
What do you mean by 'create a login page'? If this was a paper prototype, close by including a photo of the prototype. If an HTML/CSS prototype, close by linking to a commit.

Requires a label and an assignee.

**Comment by rsgc-wrana-m** [comment]
assigned myself
